SELECT DEFAULT_CHARACTER_SET_NAME, DEFAULT_COLLATION_NAME FROM 
information_schema.SCHEMATA S
WHERE schema_name = 'marira'
AND
(DEFAULT_CHARACTER_SET_NAME != 'utf8'
    OR
 DEFAULT_COLLATION_NAME not like 'utf8%');